name: Build and deploy ASP.Net Core app to Azure Web App - NumberConverterBackend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
      
      - name: List solution structure
        run: |
          dir /s /b *.sln *.csproj

      - name: Build solution
        run: |
          dotnet build NumberConverterBackend\NumberConverterBackend.sln --configuration Release

      - name: Run tests
        run: |
          dotnet test NumberConverterBackend\NumberConverterBackend.sln --configuration Release --no-build

      - name: Publish main project
        run: |
          $publishPath = "$env:RUNNER_TEMP\publish"
          dotnet publish NumberConverterBackend\NumberConverterBackend\NumberConverterBackend.csproj -c Release -o "$publishPath"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ runner.temp }}\publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EB641445DCFC468FA6F45F0935EAF8A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DF9761E1853A4367A8458C1708D43553 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1280850E1D304F449185EB9EF63A031A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'NumberConverterBackend'
          slot-name: 'Production'
          package: .
          
